/**
 * Utility for exporting table data to Excel (CSV) and triggering browser print.
 */

export const exportToCSV = (filename, headers, data, fieldMapping) => {
  const csvRows = [];

  // Add headers
  csvRows.push(headers.join(','));

  // Add data rows
  for (const row of data) {
    const values = fieldMapping.map(field => {
      const val = row[field];
      const escaped = ('' + (val || '')).replace(/"/g, '""');
      return `"${escaped}"`;
    });
    csvRows.push(values.join(','));
  }

  const csvString = csvRows.join('\n');
  const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  if (link.download !== undefined) {
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', `${filename}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
};

export const printTable = (title, headers, data, fieldMapping, companyInfo = null, meta = {}) => {
  const win = window.open('', '_blank');

  const tableRows = data.map(row => `
    <tr>
      ${fieldMapping.map(field => `<td>${row[field] || ''}</td>`).join('')}
    </tr>
  `).join('');

  win.document.write(`
    <html>
      <head>
        <title>${title}</title>
        <style>
          body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; color: #333; }
          .header { display: flex; justify-content: space-between; border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 30px; }
          .company-info h1 { margin: 0; color: #0284c7; font-size: 24px; }
          .company-info p { margin: 4px 0; font-size: 13px; color: #666; }
          .report-meta { text-align: right; }
          .report-meta h2 { margin: 0; color: #475569; font-size: 18px; text-transform: uppercase; }
          .report-meta p { margin: 3px 0; font-size: 11px; color: #64748b; }
          .report-title { text-align: center; font-size: 22px; font-weight: 800; text-decoration: underline; margin: 30px 0; letter-spacing: 1px; color: #0284c7; }
          table { width: 100%; border-collapse: collapse; margin-top: 10px; }
          th { background: #f1f5f9; border: 1px solid #e2e8f0; padding: 12px; font-size: 13px; text-transform: uppercase; text-align: left; }
          td { border: 1px solid #e2e8f0; padding: 12px; font-size: 13px; }
          tr:nth-child(even) { background-color: #f8fafc; }
          .footer { margin-top: 50px; text-align: center; font-size: 11px; color: #94a3b8; border-top: 1px dashed #e2e8f0; padding-top: 20px; }
          @media print {
            body { padding: 0; }
            .header { border-bottom-color: #000; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="company-info">
            <h1>${companyInfo?.CompanyName || 'FA SYSTEM'}</h1>
            <p>${companyInfo?.Address || ''}</p>
            <p>
              ${companyInfo?.Contact ? `Contact: ${companyInfo.Contact}` : ''}
              ${companyInfo?.FaxNo ? ` | Fax: ${companyInfo.FaxNo}` : ''}
            </p>
            <p>${companyInfo?.Email || ''}</p>
            <p style="font-size: 11px; margin-top: 5px; color: #475569;">
                ${[
      companyInfo?.NTNo ? `NTN: ${companyInfo.NTNo}` : '',
      companyInfo?.GSTNo ? `GST: ${companyInfo.GSTNo}` : '',
      companyInfo?.GovtNo ? `Govt No: ${companyInfo.GovtNo}` : '',
      companyInfo?.IATACode ? `IATA: ${companyInfo.IATACode}` : ''
    ].filter(Boolean).join(' | ')}
            </p>
          </div>
          <div class="report-meta">
            <h2>${title}</h2>
            ${meta.fromDate ? `<p>Period: ${meta.fromDate} to ${meta.toDate || 'Present'}</p>` : ''}
            ${meta.fiscalYear ? `<p>Fiscal Year: ${meta.fiscalYear}</p>` : ''}
            ${meta.location ? `<p>Location: ${meta.location}</p>` : ''}
            <p>Printed on: ${new Date().toLocaleString()}</p>
            <p>Records: ${data.length}</p>
          </div>
        </div>
        <div class="report-title">${title}</div>
        <table>
          <thead>
            <tr>
              ${headers.map(h => `<th>${h}</th>`).join('')}
            </tr>
          </thead>
          <tbody>
            ${tableRows}
          </tbody>
        </table>
        <div class="footer">
          Generated by MACCANSOFT Business Suite
        </div>
        <script>
          window.onload = () => {
            window.print();
          }
        </script>
      </body>
    </html>
  `);
  win.document.close();
};
